apiVersion: v1
kind: Service
metadata:
  name: Loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: httpd
      protocol: TCP
      port: 80
      targetPort: 80  # Ensure that the target port inside the container matches.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Loadbalancer-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: akshay/newimage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # Ensure the container exposes port 80
